CREATE TABLE Usuarios (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nome NVARCHAR(200) NOT NULL,
    Email NVARCHAR(200) NOT NULL,
    Senha NVARCHAR(500) NOT NULL,
    DataCriacao DATETIME NOT NULL DEFAULT GETDATE()
);